### ISSUE TITLE
kirjete toimikud

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/memoriaal.ee#1]
PC tähisega viidete vaste: ERAF.130sm.2.2;
leida selle viitega nimedele persoon repr. kaartide nimekirjast (kirjekoodiga RK)

**Comment by mitselek** [comment]
tõin välja kõik [PC] kirjed, millele siiani pole RK vastet leitud
https://docs.google.com/spreadsheets/d/1fAoRLbmWTfIBiMxnH36e2pRK2d08Zs55Usagkmbd2e8/edit#gid=0

**Comment by mitselek** [comment]
Kas tegelt peab see ERAF.130sm.2.2 toimiku viide olema hoopis kõigi RK kirjetel?

**Comment by UlleKr** [comment]
Nendel ainult, mis meil õnnestub tuvastada. Ma kahtlustan, et osa kaarte on
ühest kartoteegist teise tõstetud (need, millele vastet ei leia).

**Comment by mitselek** [comment]
Lisatud 'ERAF.130sm.2.2' toimik:
- Juba seotud RK kirjetele;
- Kõigile (põhiliselt R81) kirjetele, kus kirjeteksti viites sisaldub **PC**
