### ISSUE TITLE
R81-000880 ja R81-000888 on identsed, aga isikud on erinevad

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/memoriaal.ee#10]
R81-000888 Dmitri Baranov järel peaks olema tekst;
BARANOV, Dmitri, Ivan, venelane, s. 1925 Petserimaa, eluk. Tallinn Vene-Balti 126-13, tööline, arr. 18.02.52 Tallinn Vene-
Balti 126-13, trib. 13.05.52, §58-1a, 25+5a. Saatus teadmata. (10) [PC]

eelmised ja järgmised kirjed paistavad õiged olema

**Comment by mitselek** [comment]
olemas
