### ISSUE TITLE
0000211494 =? 0000202562

### ISSUE THREAD

**Issue by mitselek** [memoriaal/memoriaal.ee#14]
- 131SM-1446: Teder, Elme, Jaan. Sünd Naine. valla komsorg; bandiitide poolt tapetud 1949-05-05 Rõuge vald. [131-156-226; 131-167-100]

=?

- PR-1136179: TEDER, ÕILME, JAAN, ema eesnimi OLGA, naine. Sünd: 1925-04-24, KRABI V. Raamat: VARSTU V kd 4 lk 175.
- R82-000803: TEDER, Õilme, Jaan n, s. 1925, eluk. Võrumaa Rõuge, valla komsorg. Metsavendade poolt tapetud 05.05.1949. (29) [EC 156-226]
- R86-022812: TEDER, Õilme. Sünd: 1925. Surm: 1949. R8/2.

**Comment by UlleKr** [comment]
Samad, jah (sama viide). Ühendasin isikud.
