### ISSUE TITLE
Aruanne: uued kivikirjed

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/memoriaal.ee#2]
Seal võib olla mitu nime, kellel on tegelikult kaks kivi (üks pime ja teine mitte). Aga kuvab uute nimekirjas.
Ma lahendust ei oska pakkuda: üks variant oli pime kivi fantoomisiku juurde ümber tõsta.

Vt. näiteks 0000080371 Karl Vaasmann

Tegelikult, kui lisada aruandesse veel veerud EMI ja Kivi, siis on ju kohe näha, kellel on kivi juba olemas?

**Comment by mitselek** [comment]
Ehk on hoopis selles asi, et meil on see kivide loogika halvasti disainitud;

Kivikirjed on teistest tiba erinevad - neile on sisse kirjutatud erinevad eluetapid:
- värske kivikirje - veel pole tahvlil aga peab sinna minema
- tahvlikirje
- vale tahvlikirje

Kui ma kõik kivikirjed vastava märkega varustan, muutub meil kohe elu lihtsaks, mh?

**Comment by UlleKr** [comment]
No tee proovi! Praegu on mureks see, et kui teen ühe tahvlikirje valeks, ilmub teine nimi uute kivikirjete aruandesse. Kivi märget ära võtta ei saa.

**Comment by UlleKr** [comment]
Näh, mul läks juba meelest ära, et see nimekiri sisaldab ka neid, kel kivi juba olemas, aga ma ei oska neid sealt üles leida.

**Comment by mitselek** [comment]
uued kivikirjed aruanne on nüüd uutmoodi.
seal peaks esiteks tähelepanu pöörama neile ridadele, kus embkumb kirjete veerg tühi on. neid persoone peaks desktopil uurima ja liigse 'x - kivi' eemaldama

**Comment by mitselek** [comment]
praegu puudub [kodulehe lisatahvlite nimekirjast](https://www.memoriaal.ee/sein/#lisatahvel) kümmekond kirjet, mis on uute kivikirjete aruandes olemas.
``` sql
SELECT mem.*
FROM aruanded.uued_kivikirjed uk
left JOIN aruanded.memoriaal_ee mem ON uk.persoon = mem.id
WHERE mem.tiib != 'x'
;
```

**Comment by UlleKr** [comment]
Need on üldiselt liidetud (kahe persoonikoodiga) isikud, ehk on selles
liitmises probleem?

**Comment by mitselek** [comment]
tundub, et kodulehe lisanimekiri vajab ka parandamist
