### ISSUE TITLE
Tahvel A166

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/memoriaal.ee#3]
Palun tee kaks spreadsheeti, ühel praegune seis, teisel sisseviidud muudatustega seis. Erinevused värvikoodiga :)

**Comment by mitselek** [comment]
tegin ühe
https://docs.google.com/spreadsheets/d/1gyvfTS0UGXa1T1fOPsOsR4IX1Oh-O00YP6oS8hgIHoY/edit#gid=0
