### ISSUE TITLE
Surmakuupäevad repr_kart

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/memoriaal.ee#9]
Vaatasin, et SQLis on 105 kirjet, kus surma kohale on märgitud MeelisS.
Baasis näeb see nii välja:
https://www.memoriaal.ee/baas/?q=0000091164&f=all

Ehk annab sellega midagi ette võtta?

**Comment by mitselek** [comment]
ha!
need "kuupäevad" peaks vast kustutama sest ega MeelisS neid ka ei tea ju :bulb:

**Comment by UlleKr** [comment]
Tõsta pudru juurde, see vist näitab, kes sisestas. Aga enne peaks vaatama,
et muud asjad samadel ridadel nihkes poleks.

**Comment by mitselek** [comment]
import.repr_kart tabelis 'MeelisS' on lisatud pudrulahtrisse ja surmakuupäev on nüüd tühi.
repis.kirjed tabbelis on surm tühi ja kirje lahter värskendatus. Järgmisel publitseerimisel jõuab ka kodulehele.
